### ISSUE TITLE
[gohai] runtime panicking

### ISSUE THREAD

**Issue by yannmh** [DataDog/dd-agent#1849]
```
2015-08-20 09:52:57 Coordinated Universal Time | WARNING | checks.collector(collector.pyc:649) | GOHAI LOG | panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x514ae0, 0x5ddf5c)
	c:/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/DataDog/gohai/network.getNetworkInfo(0x10f27180, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/network/network_windows.go:38 +0x566
github.com/DataDog/gohai/network.(*Network).Collect(0x5e07d8, 0x0, 0x0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/network/network_common.go:17 +0x47
main.Collect(0x10eeb700, 0x0, 0x0)
	C:/workspace/go/src/github.com/Datadog/gohai/gohai.go:32 +0xc6
main.main()
	C:/workspace/go/src/github.com/Datadog/gohai/gohai.go:44 +0x24

goroutine 19 [finalizer wait]:
runtime.park(0x412d30, 0x5e05f4, 0x5df969)
	c:/go/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x5e05f4, 0x5df969)
	c:/go/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
	c:/go/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445
```
I've seen this issue coming multiple times from Windows machines. It's not a critical issue but it's populating logs with errors. 

Let's fix it with the 5.5.0

**Comment by olivielpeau** [comment]
I think it's been fixed by https://github.com/DataDog/gohai/pull/13 (see also https://trello.com/c/e3amjMfo/1000-bug-gohai-issue-on-windows), or is it something else ?
cc @elafarge

**Comment by elafarge** [comment]
Thanks @olivielpeau for that notice. It's indeed something that occured when the machine had no IPv6 and it's indeed been fixed a while ago (last month). That's one less thing to do for 5.5.0 :)

**Comment by yannmh** [comment]
Awesome !

**Comment by klops** [comment]
Just want to report that I still see this in EC2 windows node on agent 5.5.0. 

Also, I'm not sure if this cause the agent to restart very frequently.
I see this entry in eventlog every couple minutes "collector was unresponsive for too long. Restarting..."

**Comment by yannmh** [comment]
Hi @klops,

Sorry to hear you are experiencing this inconvenience with Datadog Agent. To answer your question, yes it might cause the collector to restart :confused: 

Gohai last updates were incorrectly shipped with Datadog Agent 5.5.0 on Windows. We released a 5.5.1 bugfix release today to address this issue among others: https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#551--09-23-2015

Would you mind trying to upgrade and tell us if you still see the problem ? Thanks

**Comment by klops** [comment]
great, thx @yannmh , looks like 5.5.1 does the trick. Agent log no longer produce this warning and collocter process does not time out and cause agent restart anymore

**Comment by yannmh** [comment]
Thanks for the reply @klops. Glad to hear it solved the issues.

**Comment by gitav** [comment]
Hi,
Datadog agent v 5.10.1 installed on windows server 2012 R2 (Windows-8.1-6.3.9600). Python 2.7.12, 32bit
In the windows eventlog appears a consecutive series of errors: "collector was unresponsive for too long". And after a series of 5 errors, this warinig: The collector Reached limit of restarts (5 tries During the last 3600s (max authorized: 5)) Not restarting ...

The event occurs approximately every four hours and the event stream of datadoghq.com shows the restarts of the agent.
