### ISSUE TITLE
5.9.1: docker_daemon _pid error

### ISSUE THREAD

**Issue by markine** [DataDog/dd-agent#2930]
Deploying dd-agent 5.9.1 using the docker-dd-agent wrapper as a Daemonset in Kubernetes 1.2.4 generates an error in docker_daemon:

```
root@dd-agent-vvvec:/# /etc/init.d/datadog-agent info -v
2016-10-19 00:00:33,103 | WARNING | dd.collector | utils.service_discovery.config(config.py:32) | No configuration backend provided for service discovery. Only auto config templates will be used.
===================
Collector (v 5.9.1)
===================

  Status date: 2016-10-19 00:00:16 (16s ago)
  Pid: 16
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0045 s
    System UTC time: 2016-10-19 00:00:33.348994

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-172-20-0-5.ec2.internal
    local-ipv4: 172.20.0.5
    local-hostname: ip-172-20-0-5.ec2.internal
    socket-hostname: dd-agent-vvvec
    public-hostname: XXXXXXXXXXXX.compute-1.amazonaws.com
    hostname: ip-172-20-0-5.ec2.internal
    instance-id: i-XXXXXXX
    public-ipv4: XXXXXXXXXX
    socket-fqdn: dd-agent-vvvec

  Checks
  ======

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check

    docker_daemon
    -------------
      - instance #0 [ERROR]: "'_pid'"
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 771, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 254, in check
            self._report_performance_metrics(containers_by_id)
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 525, in _report_performance_metrics
            self._report_cgroup_metrics(container, tags)
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 543, in _report_cgroup_metrics
            stat_file = self._get_cgroup_from_proc(cgroup["cgroup"], container['_pid'], cgroup['file'])
        KeyError: '_pid'

      - Collected 51 metrics, 0 events & 2 service checks

    kubernetes
    ----------
      - instance #0 [OK]
      - Collected 206 metrics, 0 events & 5 service checks


  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.9.1)
===================

  Status date: 2016-10-19 00:00:31 (1s ago)
  Pid: 13
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 4
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.9.1)
===================

  Status date: 2016-10-19 00:00:31 (2s ago)
  Pid: 15
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 447 bytes
  Queue Length: 1
  Flush Count: 13
  Transactions received: 5
  Transactions flushed: 4
  Transactions rejected: 0

```

**Comment by markine** [comment]
FYI adding a little debugging around that code block:

```
    def _report_cgroup_metrics(self, container, tags):
        if '_pid' not in container:
            self.log.error('_report_cgroup_metrics: _pid not in container')
            return
        else:
            self.log.error('_report_cgroup_metrics: _pid in container')
        ...
```

Shows that _pid is missing ~60% of the time for my environment. What is the meaning of this?

**Comment by arobson** [comment]
Getting this consistently on about half of our servers running kubernetes 1.4.0, in AWS using the `datadog/docker-dd-agent:latest` (agent reports version 5.9.1) image with the recommended daemonset manifest. This only recently started happening so it makes me wonder if it's the result of a recent change in the agent that we got as a result of deploying updates to our configuration that also pulled new versions of that image/tag.

**Comment by sharebear** [comment]
I'm also suffering from this problem. Adding in some debugging code I came to the (perhaps incorrect) conclusion that it is pods in the kube-system namespace causing issues so I'm trying to use the include + exclude rules to only include the images I want but reading the code I don't understand at all how that is supposed to work as documented (I'll create a separate issue for that tomorrow).

Anyone got a workaround for this? I see that it has been open for over two weeks.

**Comment by sharebear** [comment]
I created a python script by copy-pasting and modifying a little the DockerDaemon check to take a closer look at which images aren't getting _pid assigned and running my script below I get the following output

```
root@dd-agent-lkzer:/opt/datadog-agent/agent# /opt/datadog-agent/embedded/bin/python images_without_pid.py  
u'gcr.io/google_containers/kube-proxy:v1.4.3'
u'gcr.io/google_containers/pause-amd64:3.0'
```

I see that there is functionality coming in 9.10 that will filter out pause containers by default https://github.com/DataDog/dd-agent/commit/7946ff9d8f1fa4276a99d38cb53df2e67118efad#diff-c715063ea0754a0dee972523b2db6dcf

Is it possible to get a docker image running the 9.10 RC without too much hassle?

```python
import os
from utils.dockerutil import DockerUtil, MountException
import re

CONTAINER_ID_RE = re.compile('[0-9a-f]{64}')


def _is_container_cgroup(line, selinux_policy):
    if line[1] not in ('cpu,cpuacct', 'cpuacct,cpu', 'cpuacct') or line[2] == '/docker-daemon':
        return False
    if 'docker' in line[2]:  # general case
        return True
    if 'docker' in selinux_policy:  # selinux
        return True
    if line[2].startswith('/') and re.match(CONTAINER_ID_RE, line[2][1:]):  # kubernetes
        return True
    return False

def _get_and_count_containers(docker_client, custom_cgroups=False):
    """List all the containers from the API, filter and count them."""

    containers = docker_client.containers(all=True, size=False)

    containers_by_id = {}

    for container in containers:
        container_name = DockerUtil.container_name_extractor(container)[0]

        containers_by_id[container['Id']] = container

        # grab pid via API if custom cgroups - otherwise we won't find process when
        # crawling for pids.
        if custom_cgroups:
            inspect_dict = docker_client.inspect_container(container_name)
            container['_pid'] = inspect_dict['State']['Pid']
    return containers_by_id

# proc files
def _crawl_container_pids(docker_util, container_dict, custom_cgroups=False):
    """Crawl `/proc` to find container PIDs and add them to `containers_by_id`."""
    proc_path = os.path.join(docker_util._docker_root, 'proc')
    pid_dirs = [_dir for _dir in os.listdir(proc_path) if _dir.isdigit()]

    if len(pid_dirs) == 0:
        print("Unable to find any pid directory in {0}. "
                     "If you are running the agent in a container, make sure to "
                     'share the volume properly: "/proc:/host/proc:ro". '
                     "See https://github.com/DataDog/docker-dd-agent/blob/master/README.md for more information. "
                     "Network metrics will be missing".format(proc_path))
        return container_dict

    for folder in pid_dirs:

        try:
            path = os.path.join(proc_path, folder, 'cgroup')
            with open(path, 'r') as f:
                content = [line.strip().split(':') for line in f.readlines()]

            selinux_policy = ''
            path = os.path.join(proc_path, folder, 'attr', 'current')
            if os.path.exists(path):
                with open(path, 'r') as f:
                    selinux_policy = f.readlines()[0]
        except IOError, e:
            pass
            #  Issue #2074
            #print("Cannot read %s, "
            #               "process likely raced to finish : %s" %
            #               (path, str(e)))
        except Exception as e:
            print("Cannot read %s : %s" % (path, str(e)))
            continue

        try:
            for line in content:
                if _is_container_cgroup(line, selinux_policy):
                    cpuacct = line[2]
                    break
            else:
                continue

            matches = re.findall(CONTAINER_ID_RE, cpuacct)
            if matches:
                container_id = matches[-1]
                if container_id not in container_dict:
                    print("Container %s not in container_dict, it's likely excluded", container_id)
                    continue
                container_dict[container_id]['_pid'] = folder
                container_dict[container_id]['_proc_root'] = os.path.join(proc_path, folder)
            elif custom_cgroups:  # if we match by pid that should be enough (?) - O(n) ugh!
                for _, container in container_dict.iteritems():
                    if container.get('_pid') == int(folder):
                        container['_proc_root'] = os.path.join(proc_path, folder)
                        break

        except Exception, e:
            print("Cannot parse %s content: %s" % (path, str(e)))
            continue
    return container_dict

docker_util = DockerUtil()
docker_client = docker_util.client
custom_cgroups = False

containers_by_id = _get_and_count_containers(docker_client, custom_cgroups)
containers_by_id = _crawl_container_pids(docker_util, containers_by_id, custom_cgroups)

from pprint import pprint

for k, v in containers_by_id.iteritems():
    if not "_pid" in v:
        pprint(v['Image'])
```

**Comment by sharebear** [comment]
I forgot one thing... setting custom_cgroups = True actually allows all containers to be assigned a _pid. Is that also a sane temporary workaround?

**Comment by hkaj** [comment]
Hi @sharebear 
Using custom_cgroups is the recommended workaround indeed. It simply uses the docker api to retrieve the pid instead of relying on walking the file system. It's slower though, that's why it's not enabled by default (could be an issue if you run a large number of containers).

The feature you're talking about is going out with 5.10 which will land in a few days.

**Comment by dddpaul** [comment]
I have the same problem when running dd-agent on the nodes of Docker 1.12 Swarm cluster. The only workaround I could manage it's to permit supervisord and collector running under root user.

**Comment by chitopunk** [comment]
I'm having this issue with 5.10.1 

====================
Collector (v 5.10.1)
====================

.............

    docker_daemon
    -------------
      - instance #0 [ERROR]: "'_pid'"
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 767, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 230, in check
            self._report_performance_metrics(containers_by_id)
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 489, in _report_performance_metrics
            self._report_cgroup_metrics(container, tags)
          File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 507, in _report_cgroup_metrics
            stat_file = self._get_cgroup_from_proc(cgroup["cgroup"], container['_pid'], cgroup['file'])
        KeyError: '_pid'

      - Collected 26 metrics, 1 event & 1 service check

**Comment by Brian-McM** [comment]
I'm having these issues as well with 5.10.1. Could we please get an update on this? it's been about a month and a half since there was anything on this.

**Comment by TimLudwinski** [comment]
I'm having this issue too.  Trying the workaround `custom_cgroups: true` gives this new error message: `IOError: [Errno 2] No such file or directory: '/host/proc/0/cgroup'`.

**Comment by geriljaSA** [comment]
I get the same error as in the previous message. Running latest agent on 3 docker nodes as docker containers. Had to set `custom_cgroups: true` to get past the initial error but now gets `IOError: [Errno 2] No such file or directory: '/host/proc/0/cgroup'` This is a rather large issue for us as we just purchased enterprise Datadog to get Docker monitoring up and running for our clusters. When will this be fixed?

**Comment by aalimovs** [comment]
Getting the same `instance #0 [ERROR]: "'_pid'"` on a brand new Kops cluster on AWS.

Setting `custom_cgroups: true` doesn't help, throws `instance #0 [ERROR]: "[Errno 2] No such file or directory: '/proc/1744/cgroup'"`

**Comment by itajaja** [comment]
same here. kops 1.4 on aws

**Comment by truthbk** [comment]
For those still having issue after enabling `custom_cgroups`, symptoms are addressed by https://github.com/DataDog/dd-agent/pull/3205. That particular PR has now been closed due to the ongoing SDK transition into two (https://github.com/DataDog/integrations-core/pull/237 and https://github.com/DataDog/dd-agent/pull/3218). 

If you want to try it out (at your own risk 😄 ), I would recommend testing the check out in state (commit): https://github.com/DataDog/dd-agent/blob/98836c7975d37a866c650350897bf6be96712054/checks.d/docker_daemon.py. 

Still some more investigation is necessary to determine if there's something else underlying the issue that we might need to understand and that could require additional fixing.

**Comment by truthbk** [comment]
Hi all! Just a quick note letting you know that the fix I mentioned in my previous comment was released with our 5.12.0 agent (released 03/22/2017). As far as we've been able to reproduce the issue was due to the existence of cached containers that raced to stoppage before re-caching, and thus returning a PID of zero when queried. That was the source of the issue you guys had been experiencing and the fix merged should prevent it from happening in the future.

Thank you all for your patience! 🙇

**Comment by markine** [comment]
@truthbk The 5.12.0 release seems to be running fine now with kubernetes 1.2.

```
2017-03-22 21:59:32,747 | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Collector (v 5.12.0)
====================

  Status date: 2017-03-22 21:59:31 (1s ago)
  Pid: 22
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======
  
    NTP offset: 0.0057 s
    System UTC time: 2017-03-22 21:59:33.315258
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    ec2-hostname: ip-172-20-0-90.ec2.internal
    local-ipv4: 172.20.0.90
    local-hostname: ip-172-20-0-90.ec2.internal
    socket-hostname: dd-agent-srbwq
    public-hostname: XXXXXXXXXXXXX.compute-1.amazonaws.com
    hostname: i-XXXXXXXXXXXXX
    instance-id: i-XXXXXXXXXXXXX
    public-ipv4: XXXXXXXXXXXXX
    socket-fqdn: dd-agent-srbwq
  
  Checks
  ======
  
    fluentd (5.12.0)
    ----------------
      - instance #0 [OK]
      - Collected 3 metrics, 0 events & 1 service check
  
    kubernetes (5.12.0)
    -------------------
      - instance #0 [OK]
      - Collected 132 metrics, 0 events & 4 service checks
  
    ntp (5.12.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk (5.12.0)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks
  
    docker_daemon (5.12.0)
    ----------------------
      - instance #0 [OK]
      - Collected 70 metrics, 1 event & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

====================
Dogstatsd (v 5.12.0)
====================

  Status date: 2017-03-22 21:59:27 (6s ago)
  Pid: 16
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 257
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.12.0)
====================

  Status date: 2017-03-22 21:59:32 (1s ago)
  Pid: 15
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 4712 bytes
  Queue Length: 1
  Flush Count: 890
  Transactions received: 524
  Transactions flushed: 523
  Transactions rejected: 0
  API Key Status: API Key is valid
  

======================
Trace Agent (v 5.12.0)
======================

  Not running (port 8126)
```

**Comment by aalimovs** [comment]
Hi everyone,

It seems `5.12.0` helped, but part of the issue is still there?

I don't see cgroup errors anymore in the info output. However, I noticed I can only see 13 docker metrics on the "Summary" page, and it seems not all tags are coming through? (e.g. I see docker.mem.rss with ~20 docker_image tags and docker.mem.in_use has only 4 docker_image tags).

Raised with support and noticed that `collector.log` complains about cgroup again, while there's no metnion about this in the info output.

```
IOError: [Errno 2] No such file or directory: '/host/proc/21571/cgroup'
    self._report_cgroup_metrics(container, tags)
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 670, in _report_cgroup_metrics
    stat_file = self._get_cgroup_from_proc(cgroup["cgroup"], container['_pid'], cgroup['file'])
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 980, in _get_cgroup_from_proc
    return DockerUtil.find_cgroup_from_proc(self._mountpoints, pid, cgroup, self.docker_util._docker_root) % (params)
  File "/opt/datadog-agent/agent/utils/dockerutil.py", line 368, in find_cgroup_from_proc
```

We've spinned up a Kubernetes cluster using `kops` 1.5.3 using the default image. So we assume we're not the only ones with the same issue. @itajaja I saw you mentioned you're using `kops` as well, can you confirm if you see the same?

(for Datadog team, there's an example in the 92679 ticket)
